/** @type {import('tailwindcss').Config} */
import plugin from "tailwindcss/plugin";

module.exports = {
  content: ["./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./src/scss/**/*.scss"],
  darkMode: 'class',
  // important: true,
  safelist: [
    "dark",
    "header-transition",
    "bg-transparent",
    "text-grey",
    "!text-grey",
    "text-white",
    "!text-white",
    "text-white/50",
    "text-grey/50",
    "bg-grenadier",
    "bg-citrine",
    "bg-white",
    "bg-white/20",
    "bg-spring-wood-light",
    "bg-spring-wood",
    "bg-alto",
    "bg-alto/20",
    "border-grey",
    "border-white",
    "opacity-0",
    "opacity-100",
    "[&.open]:border-[#C5B0AC]",
    "hover:text-grenadier",
    "placeholder:text-grey",
    "placeholder:text-white",
    "bg-grey",
    "bg-grey/50",
    "bg-white/50",
    "[&.open]:border-white/50",
    "text-white",
    "bg-spring-wood",
    "lg:text-grey",
    "lg:text-white",
  ],
  theme: {
    screens: {
      xs: "540px",
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      lg_992: '992px',
    },
    fontFamily: {
      'Syne': ['"Syne", sans-serif'],
      'gallery_modernregular': ['"gallery_modernregular", sans-serif'],
    },
    extend: {
      colors: {
        dark: "#121212",
        black: "rgba(0, 0, 0, 1)",
        grey: "rgba(51, 51, 51, 1)",
        white: "#F5F7F5",
      },
      keyframes: {
        rotate2: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        rotate2: 'rotate2 5s linear infinite',
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            maxWidth: "100%",
            "--tw-prose-body": theme("colors.white"),
            "--tw-prose-headings": theme("colors.grey"),
            "--tw-prose-lead": theme("colors.white"),
            "--tw-prose-links": theme("colors.grenadier"),
            "--tw-prose-bold": theme("colors.white"),
            "--tw-prose-bullets": theme("colors.white"),
            "--tw-prose-hr": theme("colors.white"),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    plugin(({ addComponents, addBase, theme }) => {
      addBase({
        body: {
          color: theme("colors.grey"),
          background: theme("colors.dark"),
          fontFamily: theme("fontFamily.Syne"),
          lineHeight: "28px",
          margin: "0",
          fontWeight: "normal",
          fontSmoothing: "antialiased",
          "-webkit-font-smoothing": "antialiased",
          "-moz-osx-font-smoothing": "grayscale",
          overflowX: "hidden",
        },
      });
      addComponents({
        h1: {
          fontSize: "5rem",
          lineHeight: "1.1",
          letterSpacing: "normal",
          fontWeight: "400",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "7rem",
            lineHeight: "1",
            letterSpacing: "-0.5px",
          },
          "@media (min-width: 1024px)": {
            fontSize: "5.6rem",
            lineHeight: "1",
            letterSpacing: "-0.5px",
          },
          "@media (min-width: 1199px)": {
            fontSize: "6.5rem",
            lineHeight: "1",
            letterSpacing: "-0.5px",
          },
          "@media (min-width: 1200px)": {
            fontSize: "6.7rem",
            lineHeight: "1",
            letterSpacing: "-0.5px",
          },
          "@media (min-width: 1400px)": {
            fontSize: "8rem",
            lineHeight: "1",
            letterSpacing: "-0.5px",
          },
          "@media (min-width: 1700px)": {
            fontSize: "11rem",
            lineHeight: "1",
            letterSpacing: "-0.5px",
          },
        },
        h2: {
          fontSize: "4rem",
          lineHeight: "1.1",
          fontWeight: "400",
          letterSpacing: "-0.5px",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "6rem",
          },
        },
        h3: {
          fontSize: "2.6rem",
          fontWeight: "400",
          lineHeight: "1.1",
          letterSpacing: "-0.5px",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "4.6rem",
          },
        },
        h4: {
          fontSize: "3.2rem",
          lineHeight: "1.3",
          fontWeight: "400",
          letterSpacing: "normal",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
        },
        h5: {
          fontSize: "2.6rem",
          lineHeight: "1.1",
          fontWeight: "400",
          letterSpacing: "normal",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "3rem",
          },
        },
        h6: {
          fontSize: "2.4rem",
          lineHeight: "1.1",
          fontWeight: "400",
          letterSpacing: "normal",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
        },
        ".h1": {
          fontSize: "4rem",
          lineHeight: "1.1",
          letterSpacing: "normal",
          fontWeight: "400",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "8rem",
            lineHeight: "1.2",
            letterSpacing: "-0.5px",
          },
        },
        ".h2": {
          fontSize: "4rem",
          lineHeight: "1.1",
          fontWeight: "400",
          letterSpacing: "-0.5px",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "6rem",
          },
        },
        ".h3": {
          fontSize: "2.6rem",
          fontWeight: "400",
          lineHeight: "1.1",
          letterSpacing: "-0.5px",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
          "@media (min-width: 640px)": {
            fontSize: "4.6rem",
          },
        },
        ".h4": {
          fontSize: "3.2rem",
          lineHeight: "1.3",
          fontWeight: "400",
          letterSpacing: "normal",
          fontFamily: theme("fontFamily.gallery_modernregular"),
          color: theme("colors.grey"),
        },
        p: {
          fontSize: "1.6rem",
          fontWeight: "300",
          lineHeight: "1.2",
          letterSpacing: "0.5px",
          color: theme("colors.black"),
        },
        a: {
          textDecoration: "none",
          cursor: "pointer",
        },
      });
    }),
  ],
}

